name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium-hub:
        image: selenium/standalone-chrome:latest  # Use standalone image with Chrome
        options: --shm-size=2g  # Optional: Increase shared memory size
        ports:
          - 4444:4444  # Expose the Selenium Hub port

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # specify the version of Python you want to use

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Step 4: Install dependencies using Poetry
      - name: Install dependencies
        run: |
          poetry install

      # Step 5: Run tests with pytest
      - name: Run tests
        run: |
          poetry run pytest -s tests/ --maxfail=1 --disable-warnings -q  # optional arguments for pytest
        env:
          SELENIUM_URL: "http://localhost:4444/wd/hub"  # Set environment variable to point to Selenium Hub
